POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen",
    "blogs": [
        {
            "title": "uusi blogi",
            "author": "mluukkai",
            "url": "http://www.uusi.blogi.fi",
            "likes": 0
        }
    ]
}