POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mluukkai",
    "password": "salainen",
    "blogs": [
        {
            "title": "tepon blogi",
            "author": "Teppo Testaaja",
            "url": "http://www.uusi.blogi.fi",
            "likes": 0
        }
    ]
}